ITSProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ITSProject.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

ITSProject/Controllers/SkolaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ITSProject.Models;
using Microsoft.AspNet.Identity;

namespace ITSProject.Controllers
{
    public class SkolaController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Skola
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Skolas.ToList());
        }

        // GET: Skola/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Skola skola = db.Skolas.Find(id);
            if (skola == null)
            {
                return HttpNotFound();
            }
            return View(skola);
        }

        // GET: Skola/Create
        [Authorize(Roles = "Admin,Employee")] //skolu moze da vidi i pravi admin i employee
        public ActionResult Create()
        {
            return View();
        }

		// POST: Skola/Create 
		[HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="Admin,Employee")]
        public ActionResult Create([Bind(Include = "Id,Naziv,AdresaReg,Opstina,PostanskiBroj,MaticniBroj,PIB,BrojRacuna,WebStranica,Pecat,Beleska")] Skola skola)
        {
            if (ModelState.IsValid)
            {

				skola.ApplicationUserID = User.Identity.GetUserId();
				db.Skolas.Add(skola);
				
				db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(skola);
        }

        // GET: Skola/Edit/5
        [Authorize(Roles = "Admin,Employee")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Skola skola = db.Skolas.Find(id);
            if (skola == null)
            {
                return HttpNotFound();
            }
            return View(skola);
        }

        // POST: Skola/Edit/5
        [HttpPost]
        [Authorize(Roles = "Admin,Employee")]
        [ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "Id,Naziv,AdresaReg,Opstina,PostanskiBroj,MaticniBroj,PIB,BrojRacuna,WebStranica,Pecat,Beleska")] Skola skola)
        {
            if (ModelState.IsValid)
            {
                db.Entry(skola).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(skola);
        }

		// GET: Skola/Delete/5
        [Authorize(Roles="Admin")] 
		public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Skola skola = db.Skolas.Find(id);
            if (skola == null)
            {
                return HttpNotFound();
            }
            return View(skola);
        }

        // POST: Skola/Delete/5//
        [Authorize(Roles="Admin")]
		[HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Skola skola = db.Skolas.Find(id);
            db.Skolas.Remove(skola);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ITSProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Aliquam porttitor pretium dui, non lobortis sem fringilla a. 
    Morbi non ultrices leo, et auctor sem. Aliquam erat volutpat. 
    Pellentesque ultricies iaculis sodales. 
    Aliquam ut nibh et risus hendrerit egestas in eget lorem. 
    Nam vitae magna scelerisque, consequat mauris imperdiet, lobortis eros. 
    Maecenas tempor metus massa, sed eleifend purus convallis non. 
    Nulla accumsan, est ac venenatis sagittis, nisi tellus volutpat purus, et venenatis dolor nunc et justo. 
    Sed condimentum est nisi, eget fringilla dui feugiat et. 
    Maecenas auctor dui a bibendum ornare. 
    Maecenas erat lacus, porta ut purus et, pretium sodales neque. Ut ut diam in neque dictum impe
    rdiet id id augue. Sed blandit lacinia urna vel aliquet.</p>

ITSProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    ITS - Visoka škola strukovnih studija za informacione tehnologije<br />
    Beograd, Savski nasip 7<br />
    <abbr title="Phone">Telefon:</abbr>
    0113333222
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
</address>

ITSProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h2>School Archive</h2>
    <p class="lead"></p>

    <p>@Html.ActionLink("List of schools", "Index", "Skola", null, new { @class = "btn btn-primary btn-large" })</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Lorem</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Nullam porta turpis a scelerisque elementum. 
            Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. 
        </p>
    </div>
    <div class="col-md-4">
        <h2>Ipsum</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Nullam porta turpis a scelerisque elementum.
            Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
        </p>
    </div>
    <div class="col-md-4">
        <h2>Design</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Nullam porta turpis a scelerisque elementum.
            Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
        </p>
    </div>
</div>